### ISSUE TITLE
Current font files do not match mocks

### ISSUE THREAD

**Issue by electrovir** [Toniq-Labs/toniq-labs-design-system#18]
Current font and weight properties do not match the visual weight of the mocks, even though the CSS styles are the same:

In code:
<img width="128" alt="Screen Shot 2022-05-07 at 19 41 57" src="https://user-images.githubusercontent.com/1205860/167278269-1b6d8fbc-7a35-4847-b10e-18f17e799e8d.png">
From mocks:
<img width="128" alt="Screen Shot 2022-05-07 at 19 43 06" src="https://user-images.githubusercontent.com/1205860/167278275-c98b1899-6f13-4954-a57b-9a95c455fb70.png">

**Comment by ponnexcodev** [comment]
Zooming out the component in storybook would have the same font. This is just how pixel vs vector rendering differs when things are small. Figma renders everything in vector hence why it looks different to prevent rasterization, but in actual application it should be how it looks like in storybook as things will be rendered in pixels.

![Screen Shot 2022-05-12 at 1 33 40 PM](https://user-images.githubusercontent.com/99699764/167999082-64738e3d-16b0-402a-a861-ed1e76c8c5b2.png)
![Screen Shot 2022-05-12 at 1 33 33 PM](https://user-images.githubusercontent.com/99699764/167999088-ad7ca629-0c9b-4077-8a3c-0199c66cf52d.png)

**Comment by electrovir** [comment]
We don't pixel perfect anyway.
