### ISSUE TITLE
Chip component

### ISSUE THREAD

**Issue by electrovir** [Toniq-Labs/toniq-labs-design-system#8]
From the mocks:
![label-component](https://user-images.githubusercontent.com/1205860/166933722-15f4e3c5-b9f3-4fb1-b51e-a4b6b3a2e4a1.png)

Looks similar to the button component, but isn't clickable. Hopefully it can share styles with the button component.

**Comment by ponnexcodev** [comment]
I think the right type for this component is chip or pill, see https://mui.com/material-ui/react-chip/ and https://ux.stackexchange.com/a/141416

**Comment by electrovir** [comment]
Good catch, updating the name.
